export const word = {
  SET_ACCOUNTS: 'SET_ACCOUNTS',
  SET_FACEBOOK_WORDS: 'SET_FACEBOOK_WORDS',
  SET_INSTAGRAM_WORDS: 'SET_INSTAGRAM_WORDS',
  SET_LINKEDIN_WORDS: 'SET_LINKEDIN_WORDS',
  SET_TWITTER_WORDS: 'SET_TWITTER_WORDS'
};
