export const SOCIAL_ACCOUNTS = {
  GET_SOCIAL: 'GET_SOCIAL',
  GET_SOCILAL_SPINNER: 'GET_SOCIAL_SPINNER',
  SET_SELECTED_ACCOUNT: 'SET_SELECTED_ACCOUNT',
  CONNECT_ACCOUNT_SPINNER: 'CONNECT_ACCOUNT_SPINNER'
};
