export const SCHEDULE = {
  SELECT_PAGE: 'SELECT_PAGE',
  SET_SCHEDULE: 'SET_SCHEDULE',
  CLEAR_POST_SCHEDULE: 'CLEAR_POST_SCHEDULE',
  POST_SPINNER: 'POST_SPINNER',
  UPDATE_POST_TIME: 'UPDATE_POST_TIME',
  GET_SCHEDULED_DRAFT_POSTS: 'GET_SCHEDULED_DRAFT_POSTS',
  MANIPULATE_SCHEDULED_DATA: 'MANIPULATE_SCHEDULED_DATA',
  SET_NEW_POST: 'SET_NEW_POST',
  UPDATE_NEW_POST_MEDIA: 'UPDATE_NEW_POST_MEDIA',
  GET_CALENDAR_DATA: 'GET_CALENDAR_DATA',
  SET_NEW_POST_DESCRIPTION: 'SET_NEW_POST_DESCRIPTION'
};
