export const PROJECT = {
  GET_PROJECTS: 'GET_PROJECTS',
  GET_PROJECTS_SPINNER: 'GET_PROJECTS_SPINNER',
  GET_PROJECTS_LOAD_MORE_SPINNER: 'GET_PROJECTS_LOAD_MORE_SPINNER',
  GET_PROJECTS_ERROR: 'GET_PROJECTS_ERROR',

  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_SPINNER: 'CREATE_PROJECT_SPINNER',
  CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR'
};
