export const globalModal = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  QUEUED_SCHEDULED: 'QUEUED_SCHEDULED',
  EDIT_POST: 'EDIT_POST',
  MODAL_CALENDAR: 'MODAL_CALENDAR',
  MODAL_CALENDAR_NEW_OR_EDIT: 'MODAL_CALENDAR_NEW_OR_EDIT'
};
