export const MEDIA = {
  SET_MEDIA: 'SET_MEDIA',
  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  SET_UPLOADED_MEDIA: 'SET_UPLOADED_MEDIA',
  SET_FILE_LIST: 'SET_FILE_LIST',
  SET_MULTIPLE_FILE_LIST: 'SET_MULTIPLE_FILE_LIST'
};
